### ISSUE TITLE
请问如果要训练我自己的数据，需要添加新标签的话，在源代码中需要修改哪些部分？

### ISSUE THREAD

**Issue by Violettttee** [taishan1994/pytorch_bert_english_ner#1]
bert的预训练模型是需要自己下载嘛？

**Comment by taishan1994** [comment]
把数据处理成mid_data下面的格式，在main.py中使用该数据就行

**Comment by Violettttee** [comment]
> 把数据处理成mid_data下面的格式，在main.py中使用该数据就行

您好，谢谢你的回复，我已经训练好模型了，但是发现保存下来的是model.pt而不是pytorch.model.bin，如果我要进行预测的话，是否还是得使用bert-base-cased中的pytorch.model.bin作为模型，并加载model.pt?另外想请问我对main中的example进行预测时，Nader Jokhadar这个名字返回的预测结果是这样的——
![image](https://github.com/taishan1994/pytorch_bert_english_ner/assets/110839053/7aa2a5c7-c64e-42d6-9354-b07055e33892)
其中的井号是本身预测的设置就是如此吗？如果我需要获取具体人名是否需要写一个具体的代码处理这个#？
